# Generated by Django 5.2.3 on 2025-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mercadopago_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway_id',
            field=models.CharField(blank=True, help_text='ID da transação no gateway de pagamento (PagBank/PagSeguro)', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_email'], name='payments_pa_payer_e_9f1a23_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_gateway_id'], name='payments_pa_payment_edcfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['preference_id'], name='payments_pa_prefere_31e198_idx'),
        ),
    ]
